In [2]:
import keras
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, BatchNormalization, Activation
from keras.models import Model
from keras.callbacks import EarlyStopping, ModelCheckpoint
from keras.optimizers import Adam
import os
import pickle
import numpy as np

In [6]:
data_example = np.random.randint(255, size=(10, 4, 6))

In [7]:
print data_example

[[[158 168 241 221  79  64]
  [233  63  42  69  12 253]
  [161 203 171   2 232  20]
  [ 32  91 130 136  98 190]]

 [[115  39  73 144 210 170]
  [176  91 187 242 163 126]
  [156  27 147 211 181 141]
  [ 69  70  24 248 151 104]]

 [[196 189 194 103 180 238]
  [154  78 101 120 198 210]
  [ 10 135  52 141  61  28]
  [ 72 231   1 132 103 230]]

 [[ 98 137  65  83 168  61]
  [ 35 180 195  70 231 249]
  [187 144 213  96  51  47]
  [ 34 108 143  40 158 111]]

 [[218 194 144 161 216 208]
  [251 240  90  53 231 219]
  [119  13 213 123 131  32]
  [116 251 102  75 101   4]]

 [[ 59 106 253 221  72 235]
  [235  83  83 224  64  27]
  [119  72 228 247  67 157]
  [140 195 132  34 199  24]]

 [[ 94 234 128 206 116  58]
  [ 18  20 203 253  92 147]
  [ 69 147 129 176 234 201]
  [176 109  73 164 115 181]]

 [[  6 155 228 247 228 138]
  [ 13 174  46 132 252 164]
  [ 57  34 248  58  10 218]
  [ 64 252  56 253  53 127]]

 [[166 245 147  66 117 234]
  [ 47 251 185  52  81 233]
  [231 156  36 225 120 138]
  [ 

In [13]:
x_train = np.empty([20, 32, 32, 3])

In [14]:
for i in range(20):
    x_train[i] = np.random.randint(255, size=(32, 32, 3))

In [15]:
print x_train[0].shape

(32, 32, 3)


In [16]:
print x_train.shape #20 examples

(20, 32, 32, 3)


In [17]:
# normalize data
x_train = x_train.astype('float32')
x_train /= 255.

In [18]:
input_img = Input(shape=(32, 32, 3))
x = Conv2D(64, (3, 3), padding='same')(input_img)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(32, (3, 3), padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(16, (3, 3), padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
encoded = MaxPooling2D((2, 2), padding='same')(x)

x = Conv2D(16, (3, 3), padding='same')(encoded)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(32, (3, 3), padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(64, (3, 3), padding='same')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(3, (3, 3), padding='same')(x)
x = BatchNormalization()(x)
decoded = Activation('sigmoid')(x)

In [19]:
model = Model(input_img, decoded)
model.compile(optimizer='adam', loss='binary_crossentropy')

In [20]:
history = model.fit(x_train, x_train,
                    batch_size=5,
                    epochs=100,
                    verbose=1,
                    shuffle=True)

Epoch 1/100
20/20 [==============================] - 1s 29ms/step - loss: 0.8028
Epoch 2/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7795
Epoch 3/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7702
Epoch 4/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7593
Epoch 5/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7530
Epoch 6/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7464
Epoch 7/100
20/20 [==============================] - 0s 10ms/step - loss: 0.7437
Epoch 8/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7381
Epoch 9/100
20/20 [==============================] - 0s 11ms/step - loss: 0.7366
Epoch 10/100
20/20 [==============================] - 0s 11ms/step - loss: 0.7322
Epoch 11/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7253
Epoch 12/100
20/20 [==============================] - 0s 9ms/step - loss: 0.7254
Epoch 13/100
20/20 [=============